# A custom, simplified GitHub Action for SFTP file deployment.
# This action is designed to be used by other workflows.
# It installs lftp, authenticates with SFTP credentials, and mirrors the local directory to the remote.

name: "Simplified SFTP Deployer"
description: "A stripped-down SFTP deployment action that mirrors a local directory to a remote host."
branding:
  icon: "upload"
  color: "blue"

inputs:
  remote-protocol:
    description: "Remote file transfer protocol (sftp)"
    required: true
    default: "sftp"
  remote-host:
    description: "Remote host"
    required: true
  remote-port:
    description: "Remote port"
    required: true
    default: 22
  remote-user:
    description: "SFTP username"
    required: true
  remote-password:
    description: "SFTP password"
    required: true
  local-path:
    description: "Local path to deploy from"
    required: true
  remote-path:
    description: "Remote path on host"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      shell: bash
      run: |
        echo "::group::Install packages"
        # We need lftp to handle the SFTP mirroring
        sudo apt-get --quiet --quiet update && sudo apt-get --quiet --quiet --no-install-recommends --yes install lftp
        echo "::endgroup::"
    
    - name: "Transfer files"
      shell: bash
      run: |
        echo "::group::Transfer files to remote host"
        
        # Use lftp to mirror the local path to the remote path.
        # This version passes the username and password directly in the URI for more reliable
        # authentication in non-interactive environments.
        # The 'mirror' command ensures all local files are copied to the remote.
        # We use 'set sftp:auto-confirm yes;' to automatically accept the host key, which is a common
        # practice in CI/CD environments where the known_hosts file is not persistent.
        lftp -c "set sftp:auto-confirm yes; open ${{inputs.remote-protocol}}://${{inputs.remote-user}}:${{inputs.remote-password}}@${{inputs.remote-host}}:${{inputs.remote-port}}; 
                  mirror --reverse --delete --verbose \"${{inputs.local-path}}\" \"${{inputs.remote-path}}\""

        echo "::endgroup::"
