# A custom GitHub Action for SFTP file deployment based on file checksums.
# This action is designed to be used by other workflows.
# It installs lftp, generates local checksums, compares them with remote checksums,
# and then pushes, removes, or updates only the files that have changed.

name: "Checksum-Based SFTP Deployer"
description: "An SFTP deployment action that uses checksums to intelligently mirror a local directory to a remote host."
branding:
  icon: "check-circle"
  color: "green"

inputs:
  remote-protocol:
    description: "Remote file transfer protocol (sftp)"
    required: true
    default: "sftp"
  remote-host:
    description: "Remote host"
    required: true
  remote-port:
    description: "Remote port"
    required: true
    default: 22
  remote-user:
    description: "SFTP username"
    required: true
  remote-password:
    description: "SFTP password"
    required: true
  local-path:
    description: "Local path to deploy from"
    required: true
  remote-path:
    description: "Remote path on host"
    required: true
  maintenance-page-path:
    description: "Path to the local maintenance page file (app_offline.htm)"
    required: true
  dry-run:
    description: "If true, the action will only print the commands without executing them."
    required: false
    default: "false"
  debug-mode:
    description: "If true, the lftp commands will run in verbose debug mode."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      shell: bash
      run: |
        echo "::group::Install packages"
        DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install --no-install-recommends -y lftp
        echo "::endgroup::"

    - name: "Generate local checksums"
      shell: bash
      run: |
        echo "::group::Generating checksums for local files"
        # First, ensure the local-path directory exists
        if [ ! -d "${{ inputs.local-path }}" ]; then
          echo "Error: Local path '${{ inputs.local-path }}' is not a directory. Exiting."
          exit 1
        fi
        
        # Change to the local deployment directory
        cd "${{ inputs.local-path }}"
        
        # Use find with -printf to generate clean paths without leading './'
        find . -type f -printf '%P\n' | xargs md5sum > checksums.txt
        
        echo "::endgroup::"
    
    - name: "Download remote checksums"
      shell: bash
      run: |
        echo "::group::Attempting to download remote checksum file"
        lftp -c "set sftp:auto-confirm yes; open ${{inputs.remote-protocol}}://${{inputs.remote-user}}:${{inputs.remote-password}}@${{inputs.remote-host}}:${{inputs.remote-port}}; \
                  get -O . \"${{inputs.remote-path}}/checksums.txt\" || rm \"./checksums.txt\"" &>/dev/null || true
        mv checksums.txt remote_checksums.txt || touch remote_checksums.txt
        echo "::endgroup::"

    - name: "Compare checksums and generate lftp commands"
      shell: bash
      id: generate_commands
      run: |
        echo "::group::Comparing checksums and preparing commands"
        
        # Sort both checksum files to enable efficient comparison with `join`
        sort -k 2,2 "${{ inputs.local-path }}/checksums.txt" > local_sorted.txt
        sort -k 2,2 remote_checksums.txt > remote_sorted.txt
        
        # Create a file to store the lftp commands
        echo "# lftp commands generated for deployment" > lftp_commands.txt
        
        # Add debug setting if enabled
        if [ "${{ inputs.debug-mode }}" == "true" ]; then
          echo "set sftp:debug 9;" >> lftp_commands.txt
        fi

        # Find files that are new or have a different checksum
        join -v 1 local_sorted.txt remote_sorted.txt | while read -r checksum file; do
          local_file="${{ inputs.local-path }}/$file"
          remote_file="${{ inputs.remote-path }}/$file"
          echo "mkdir -p \"$(dirname \"$remote_file\")\";" >> lftp_commands.txt
          echo "put \"$local_file\" -o \"$remote_file\";" >> lftp_commands.txt
        done

        # Find files that are no longer in the local directory
        join -v 2 remote_sorted.txt local_sorted.txt | while read -r checksum file; do
          case "$file" in
            "app_offline.htm")
              echo "Skipping removal of maintenance page: $file" >> lftp_commands.txt
              ;;
            wwwroot/umbraco/Data/*)
              echo "Skipping removal of Umbraco Data file: $file" >> lftp_commands.txt
              ;;
            wwwroot/umbraco/Logs/*)
              echo "Skipping removal of Umbraco Logs file: $file" >> lftp_commands.txt
              ;;
            wwwroot/media/*)
              echo "Skipping removal of Umbraco Media file: $file" >> lftp_commands.txt
              ;;
            *)
              echo "rm \"${{ inputs.remote-path }}/$file\";" >> lftp_commands.txt
              ;;
          esac
        done
        
        # Files that exist in both lists need to have their checksums compared
        join local_sorted.txt remote_sorted.txt | while read -r file local_checksum remote_checksum; do
          if [ "$local_checksum" != "$remote_checksum" ]; then
            local_file="${{ inputs.local-path }}/$file"
            remote_file="${{ inputs.remote-path }}/$file"
            echo "mkdir -p \"$(dirname \"$remote_file\")\";" >> lftp_commands.txt
            echo "put \"$local_file\" -o \"$remote_file\";" >> lftp_commands.txt
          fi
        done

        echo "bye" >> lftp_commands.txt
        echo "::endgroup::"
    
    - name: "Put site in maintenance mode"
      if: inputs.dry-run == 'false'
      shell: bash
      run: |
        echo "::group::Creating maintenance page app_offline.htm to take site offline"
        lftp -c "set sftp:auto-confirm yes; open ${{inputs.remote-protocol}}://${{inputs.remote-user}}:${{inputs.remote-password}}@${{inputs.remote-host}}:${{inputs.remote-port}}; \
                  put \"${{inputs.maintenance-page-path}}\" -o \"${{inputs.remote-path}}/app_offline.htm\""
        echo "::endgroup::"
        
    - name: "Execute lftp commands"
      if: inputs.dry-run == 'false'
      shell: bash
      run: |
        echo "::group::Executing deployment commands"
        lftp -f lftp_commands.txt
        echo "::endgroup::"

    - name: "Dry Run: Displaying commands only"
      if: inputs.dry-run == 'true'
      shell: bash
      run: |
        echo "::group::Dry Run - The following commands would have been executed:"
        cat lftp_commands.txt
        echo "::endgroup::"

    - name: "Upload new checksums file"
      if: inputs.dry-run == 'false'
      shell: bash
      run: |
        echo "::group::Uploading new checksums file"
        lftp -c "set sftp:auto-confirm yes; open ${{inputs.remote-protocol}}://${{inputs.remote-user}}:${{inputs.remote-password}}@${{inputs.remote-host}}:${{inputs.remote-port}}; \
                  put \"${{inputs.local-path}}/checksums.txt\" -o \"${{inputs.remote-path}}/checksums.txt\""
        echo "::endgroup::"

    - name: "Take site out of maintenance mode"
      if: inputs.dry-run == 'false'
      shell: bash
      run: |
        echo "::group::Removing app_offline.htm to bring site online"
        lftp -c "set sftp:auto-confirm yes; open ${{inputs.remote-protocol}}://${{inputs.remote-user}}:${{inputs.remote-password}}@${{inputs.remote-host}}:${{inputs.remote-port}}; \
                  rm \"${{inputs.remote-path}}/app_offline.htm\""
        echo "::endgroup::"