name: Deploy To Cloud

on:
  workflow_dispatch:
    inputs:
      artifactId:
        required: false
        type: string
      targetEnvironmentAlias:
        description: 'The target environment alias to deploy to'
        required: true
        type: string

  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
      targetEnvironmentAlias:
        description: 'The target environment alias to deploy to'
        required: true
        type: string
      noBuildAndRestore:
        description: 'Skip build and restore steps'
        required: false
        type: string
        default: "false"
      skipVersionCheck:
        description: 'Skip version check'
        required: false
        type: string
        default: "false"

    secrets:
      projectId:
        required: true
      umbracoCloudApiKey:
        required: true

jobs:
  startDeployment:
    name: Start Deployment
    runs-on: ubuntu-latest
    outputs:
      runningDeploymentId: ${{ steps.requestStartDeployment.outputs.deploymentId }}
    steps:
      - uses: actions/checkout@v4

      # Request to prepare a deployment
      # - sets the commit message to be used in cloud 
      # - supplies you with a deploymentId to be used in the rest of the process
      - name: Request Start Deployment
        id: requestStartDeployment
        shell: bash
        run: >
          bash ${{ GITHUB.WORKSPACE }}/.github/scripts/start_deployment.sh
          ${{ secrets.projectId }} 
          ${{ secrets.umbracoCloudApiKey }} 
          ${{ inputs.artifactId }}
          ${{ inputs.targetEnvironmentAlias }}
          "Run for ${{ github.run_number }}"
          ${{ inputs.noBuildAndRestore}}
          ${{ inputs.skipVersionCheck }}
          GITHUB

  awaitDeploymentFinished:
    name: Await deployment to finish
    runs-on: ubuntu-latest
    needs: startDeployment
    steps:
      - uses: actions/checkout@v4

      # Poll until deployment finishes 
      - name: Wait for deployment completed
        shell: bash
        env: 
          runningDeploymentId: ${{ needs.startDeployment.outputs.runningDeploymentId }}
        run: >
          bash ${{ GITHUB.WORKSPACE }}/.github/scripts/get_deployment_status.sh 
          ${{ secrets.projectId }} 
          ${{ secrets.umbracoCloudApiKey }} 
          ${{ env.runningDeploymentId }} 